<!-- Modal to add answer -->
<div class="modal fade" id="addAnswer" tabindex="-1" role="dialog" aria-labelledby="addAnswerTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="addAnswerTitle">Modal title</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php echo $this->form()->openTag($formAnswer); ?>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <?php echo $this->formLabel($formAnswer->get('label')); ?>
                            <?php echo $this->formText($formAnswer->get('label')); ?>
                            <?php echo $this->formElementErrors($formAnswer->get('label')); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <?php echo $this->formLabel($formAnswer->get('value')); ?>
                            <?php echo $this->formText($formAnswer->get('value')); ?>
                            <?php echo $this->formElementErrors($formAnswer->get('value')); ?>
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-secondary" id="addAnswerButton">Add answer</button>
            </div>
            <?php echo $this->form()->closeTag($formAnswer); ?>
        </div>
    </div>
</div>
