<?php $form->prepare(); ?>
<?= $this->form()->openTag($form); ?>
<?= $this->formRow($form->get('csrf')); ?>
    <input type="hidden" name="options" value='<?= (is_object($checkListField)?$checkListField->getOptions():''); ?>' />

<?php
$fieldset = $form->get('checklist-field');
$name = $fieldset->get('name');
?>
    <div class="row mb-2">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <?= $this->formLabel($name) ?>
            <div class="input-group mb-2 mt-2">
                <?= $this->formElement($name) ?>
                <small class="form-text text-danger"> <?= $this->formElementErrors()->render($name) ?></small>
            </div>
        </div>
    </div>
<?php
$showInOverview = $fieldset->get('showInOverview');
?>
    <div class="row mb-2">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <?php echo $this->formLabel($showInOverview); ?>
            <div class="input-group mb-2 mt-2">
                <label class="switch">
                    <?php echo $this->formCheckbox($showInOverview); ?>
                    <span class="slider round"></span>
                </label>
                <?php echo $this->formElementErrors($showInOverview); ?>
            </div>
        </div>
    </div>
    <div class="row mb-2" id="introText">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="form-group mb-2 mt-2">
                <?php
                $introText = $fieldset->get('introText');
                ?>
                <?php echo $this->formLabel($introText); ?>
                <?php echo $this->formTextArea($introText); ?>
                <?php echo $this->formElementErrors($introText); ?>
            </div>
        </div>
    </div>
<?php
$required = $fieldset->get('required');
?>
    <div class="row mb-2" id="required">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <?php echo $this->formLabel($required); ?>
            <div class="input-group mb-2 mt-2">
                <label class="switch">
                    <?php echo $this->formCheckbox($required); ?>
                    <span class="slider round"></span>
                </label>
                <?php echo $this->formElementErrors($required); ?>
            </div>
        </div>
    </div>
    <div class="row mb-2" id="requiredMessage">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="form-group">
                <?php
                $requiredMessage = $fieldset->get('requiredMessage');
                ?>
                <?php echo $this->formLabel($requiredMessage); ?>
                <?php echo $this->formText($requiredMessage); ?>
                <?php echo $this->formElementErrors($requiredMessage); ?>
            </div>
        </div>
    </div>
    <div class="row mb-2">
        <div class="col">
            <div class="form-group">
                <?php
                $checklistFieldType = $fieldset->get('checklistFieldType');
                ?>
                <?php echo $this->formLabel($checklistFieldType); ?>
                <?php
                if(is_object($checkListField)) {
                    echo $this->formSelect($checklistFieldType->setAttributes(['disabled' => 'disabled']));
                } else {
                    echo $this->formElement($checklistFieldType);
                }

                 ?>
                <?php echo $this->formElementErrors($checklistFieldType); ?>
            </div>
        </div>
    </div>
<?php
echo $this->partial('partial/checklist-fields-type-options.phtml');
?>
    <div class="row mb-2">
        <div class="col">
            <div class="form-group">
                <?php
                $parent = $fieldset->get('parent');
                ?>

                <?php echo $this->formLabel($parent); ?>
                <select name="parent" class="form-control">
                    <option value="">--Maak uw keuze--</option>
                    <?php foreach ($checkListFields AS $parentCheckListField) { ?>
                        <option <?= (is_object($checkListField) && is_object($checkListField->getParent()) && $checkListField->getParent()->getId() == $parentCheckListField->getId() ? 'selected' : '') ?>
                            value="<?= $parentCheckListField->getId(); ?>"><?= $parentCheckListField->getName(); ?></option>
                    <?php } ?>
                </select>
                <?php echo $this->formElementErrors($parent); ?>
            </div>
        </div>
    </div>
<?php
echo $this->partial('partial/answers.phtml', ['answers' => $answers, 'checkListField' => $checkListField]);
?>
    <div class="row">
        <div class="col">
            <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
        </div>
        <div class="col text-right">
            <a href="<?php echo $this->url('beheer/checklist') ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
        </div>
    </div>
<?php echo $this->form()->closeTag($form); ?>