<!-- Modal answer library -->
<div class="modal fade" id="answerLibrary" tabindex="-1" aria-labelledby="answerLibraryLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="answerLibraryTitle text-white">Vragen bibliotheek</h5>
                <button type="button" class="btn-close btn-primary" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row g-4">
                    <div class="col-sm-12 col-md-12 col-xl-12">
                        <div class="bg-secondary rounded p-4">
                            <div class="row">
                                <div class="col">
                                    <form>
                                        <div class="form-group row">
                                            <div class="col">
                                                <div class="form-group">
                                                    <label for="searchAnswerLibrary">Zoeken&hellip;</label>
                                                    <div class="input-group">
                                                        <input type="text" name="search" class="form-control" value=""
                                                               placeholder="Zoeken..."/>
                                                        <div class="input-group-append">
                                                            <button type="button" id="searchAnswerLibrary"
                                                                    class=" btn input-group-text"><i
                                                                        class="fas fa-search"></i></button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="col">
                                    <?php $formAnswer->prepare(); ?>
                                    <?= $this->form()->openTag($formAnswer) ?>
                                    <?= $this->formRow($formAnswer->get('csrf')) ?>
                                    <div class="row g4 mb-2">
                                        <div class="col">
                                            <div class="form-group">
                                                <label>Voeg antwoord toe</label>
                                                <?php
                                                $fieldset = $formAnswer->get('checklist-answer');
                                                $label = $fieldset->get('label');
                                                ?>
                                                <?php echo $this->formText($label); ?>
                                                <?php echo $this->formElementErrors($label); ?>
                                            </div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group">
                                                <label></label>
                                                <?php
                                                $value = $fieldset->get('value');
                                                ?>
                                                <?php echo $this->formText($value); ?>
                                                <?php echo $this->formElementErrors($value); ?>
                                            </div>
                                        </div>
                                    </div>
                                    <button type="button" class="btn btn-primary" id="addAnswerButton">Add answer
                                    </button>
                                    <?php echo $this->form()->closeTag($formAnswer); ?>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row mt-3">
                        <div class="col-md-auto pt-5">
                            <?php foreach ($searchLinks as $link) { ?>
                                <span class="text-secondary searchOnIndex" data-index="<?= $link ?>"><?= $link ?></span>
                                <br/>
                            <?php } ?>
                        </div>
                        <div class="col">
                            <table id="answerLibraryTable"
                                   class="table table-bordered table-hover table-striped">
                                <thead class="thead-primary">
                                <tr>
                                    <th class="text-center"><i class="fas fa-cog"></i></th>
                                    <th>Label</th>
                                    <th>Value</th>
                                </tr>
                                </thead>
                                <tbody id="resultAnswerLibraryTable">

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>