<!-- Second Page Header -->
<div class="row g-4">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <div class="bg-secondary rounded">
            <h2 class="mb-2 text-primary">Fields</h2>
        </div>
    </div>
</div>
<div class="row g-4">
    <div class="col-sm-12 col-md-12 col-xl-12">
        <div class="bg-secondary rounded">
        <?php
        $this->checkListHelper()->generateCheckListFields($checklist->getCheckListFields(), $this);
        ?>
        </div>
    </div>
</div>