<!-- Options field voor text input  -->
<div id="optionField">
    <fieldset>
        <legend>Options</legend>
        <div class="form-group row option options1 options2 options4">
            <label for="readonly" class="col-sm-2 col-form-label">Read only</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="readonly" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="form-group row option options1 options2 options4">
            <label for="disabled" class="col-sm-2 col-form-label">Disabled</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="disabled" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="form-group row option options1 options4">
            <label for="maxlength" class="col-sm-2 col-form-label">Max length</label>
            <div class="col-sm-auto">
                <label class="switch">
                    <input type="checkbox" name="maxlength" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
            <div class="col-sm-2">
                <input type="number" value="" class="form-control" min="1" max="255" name="maxLengthValue"/>
            </div>
        </div>
        <div class="form-group row option options1 options2 options4">
            <label for="Autofocus" class="col-sm-2 col-form-label">autofocus</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="autofocus" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="form-group row option options1 options2">
            <label for="prependappend" class="col-sm-2 col-form-label">Prepend/Append</label>
            <div class="col-sm-auto">
                <label class="switch">
                    <input type="checkbox" name="prependappend" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
            <div id="showPrependAppend" class="col">
                <div class="row">
                    <div class="col-sm-auto">
                        <label class="container" style="float:left">Prepend
                            <input type="radio" checked="checked" name="preapp" value="pre"/>
                            <span class="checkmark"></span>
                        </label>
                        <label class="container" style="float:left">Append
                            <input type="radio" name="preapp" value="app" />
                            <span class="checkmark"></span>
                        </label>
                    </div>
                    <div class="col-sm-2">
                        <input type="text" value="" placeholder="VB: ml" class="form-control" name="apppreinput"/>
                    </div>

                    <div class="col-sm-2">
                        icon picker
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group row option options4">
            <label for="resize" class="col-sm-2 col-form-label">Resize</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="resize" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="form-group row option options4">
            <label for="readonly" class="col-sm-2 col-form-label">Afmeting</label>
            <div class="col-sm-auto">
                <label class="switch">
                    <input type="checkbox" name="measurements" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
            <div id="textareaMeasurements" class="col">
                <div class="row">
                    <div class="col-sm-2">
                        <input type="text" value="" placeholder="width" class="form-control" name="textareawidth"/>
                    </div>
                    <div class="col-sm-2">
                        <input type="text" value="" placeholder="height" class="form-control" name="textareaheigt"/>
                    </div>
                    <div class="col-sm-2">
                        <select class="form-control" name="measurementsType">
                            <option value="px" selected>px</option>
                            <option value="%">%</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</div>
