<div id="options1" class="optionField">
    <fieldset>
        <legend>Options</legend>
        <div class="form-group row">
            <label for="readonly" class="col-sm-2 col-form-label">Read only</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="readonly" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="form-group row">
            <label for="disabled" class="col-sm-2 col-form-label">Disabled</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="disabled" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="form-group row">
            <label for="maxlength" class="col-sm-2 col-form-label">Max length</label>
            <div class="col-sm-auto">
                <label class="switch">
                    <input type="checkbox" name="maxlength" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
            <div class="col-sm-2">
                <input type="number" value="255" class="form-control" min="1" max="255" name="maxLengthValue"/>
            </div>
        </div>
        <div class="form-group row">
            <label for="autocomplete" class="col-sm-2 col-form-label">Autocomplete</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="autocomplete" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>
        <div class="form-group row">
            <label for="Autofocus" class="col-sm-2 col-form-label">autofocus</label>
            <div class="col-sm-10">
                <label class="switch">
                    <input type="checkbox" name="autofocus" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
        </div>

        <div class="form-group row">
            <label for="Autofocus" class="col-sm-2 col-form-label">Prepend/Append</label>
            <div class="col-sm-auto">
                <label class="switch">
                    <input type="checkbox" name="prependappend" value="1">
                    <span class="slider round"></span>
                </label>
            </div>
            <div id="showPrependAppend" class="col">
                <div class="row">
                    <div class="col-sm-auto">
                        <label class="container" style="float:left">Prepend
                            <input type="radio" checked="checked" name="preapp" value="pre"/>
                            <span class="checkmark"></span>
                        </label>
                        <label class="container" style="float:left">Append
                            <input type="radio" name="preapp" value="app" />
                            <span class="checkmark"></span>
                        </label>
                    </div>
                    <div class="col-sm-2">
                        <input type="text" value="" placeholder="VB: ml" class="form-control" name="apppreinput"/>
                    </div>

                    <div class="col-sm-2">
                        <button class="btn btn-secondary" id="target" data-icon="" role="iconpicker"
                                data-footer="false" data-search="false"></button>
                    </div>
                </div>
            </div>
        </div>

    </fieldset>
</div>

<div id="options2" class="optionField">
    <fieldset>
        <legend>Options</legend>
    </fieldset>

</div>

<div id="options6" class="optionField">
    <fieldset>
        <legend>Options</legend>
    </fieldset>

</div>