<?php
$this->headTitle('Add Checklist');
$this->mainMenu()->setActiveItemId('checklistbeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'CheckList' => $this->url('beheer/checklist'),
    'Add CheckList' => $this->url('beheer/checklist', ['action' => 'add'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
    <!-- Page Header -->
    <div class="row">
        <h1 class="col">ADD CHECKLIST ITEM</h1>
    </div>
    <!-- Breadcrumbs -->
    <div class="row">
        <div class="col">
            <?= $this->pageBreadcrumbs()->render(); ?>
        </div>
    </div>
<?php echo $this->form()->openTag($form); ?>
<?php foreach ($checkListFields AS $checkListField) { ?>
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label><?php echo $checkListField->getName(); ?><?php echo($checkListField->getRequired() == 1 ? '*' : '') ?></label>


                <?php
                if ($checkListField->getChecklistFieldType()->getFormType() == 'text') {
                    echo $this->partial('partials/input-text.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'number') {
                    echo $this->partial('partials/input-number.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'checkbox') {
                    echo $this->partial('partials/input-checkbox.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'textarea') {
                    echo $this->partial('partials/input-textarea.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'date') {
                    echo $this->partial('partials/input-datum.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'email') {
                    echo $this->partial('partials/input-email.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'time') {
                    echo $this->partial('partials/input-time.phtml', array('checkListField' => $checkListField));
                }
                if ($checkListField->getChecklistFieldType()->getFormType() == 'url') {
                    echo $this->partial('partials/input-url.phtml', array('checkListField' => $checkListField));
                }
                ?>
            </div>
        </div>
    </div>
    <?php
}
?>
    <div class="row">
        <div class="col">
            <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
        </div>
        <div class="col text-right">
            <a href="<?php echo $this->url('beheer/checklist', ['action' => 'show', 'id' => $checklist->getId()]) ?>"
               class="btn btn-dark" title="Annuleren">Annuleren</a>
        </div>
    </div>
<?php echo $this->form()->closeTag($form); ?>