<?php
$value = '';
if(is_object($checklistitem))
{
    $values = $checklistitem->getItemContent();
    $value = $values[$checkListField->getFormFieldName()];
}
?>


<?php

foreach ($checkListField->getAnswers() AS $answer) { ?>

    <br/><input <?= ($checkListField->getRequired() == 1? 'required':'') ?> type="<?=$checkListField->getChecklistFieldType()->getFormType(); ?>" name="<?= $checkListField->getId(); ?>" value="<?= $answer->getValue(); ?>" />&nbsp;<?= $answer->getLabel(); ?>

<?php
}
?>
