<?php
$value = '';
if(is_object($checklistitem))
{
    $values = $checklistitem->getItemContent();
    $value = $values[$checkListField->getFormFieldName()];
}

/*
 * Get options from check list field
 */

$options = $checkListField->getOptionsAsArray();


/*
 * Check if measurements is checked and get width, height and type (% or px)
 */
$measurements = (array_key_exists('measurements',$options??[]) &&
array_key_exists('on',$options['measurements'])? $options['measurements']:false);
$measurementsWidth = $measurements['width'];
$measurementsHeight = $measurements['height'];
$measurementsType = $measurements['type'];

$textAreaStyle = null;
$measurementStyle = null;
$resizeStyle = null;
if($measurements) {
    $measurementStyle = 'width:'.$measurementsWidth.$measurementsType.'!important; height:'.$measurementsHeight.$measurementsType.'!important;';
}

/*
 * Check if resized is checked
 */
$resize = (array_key_exists('resize',$options??[])? $options['resize']: false);
if(!$resize) {
    $resizeStyle = 'resize:none;';
} else {
    $resizeStyle = 'resize:both;';
}


if(!empty($measurementStyle) || !empty($resizeStyle)) {
    $textAreaStyle = 'style="' . $measurementStyle . $resizeStyle . '"';
}

?>
<textarea class="form-control"
    <?php echo ($checkListField->getRequired() == 1? 'required':'') ?>
    name="<?= $checkListField->getId(); ?>"
    <?= $textAreaStyle; ?>
    >
    <?php echo $value; ?>
</textarea><br/>
