<?php

use Symfony\Component\VarDumper\VarDumper;

$value = '';
if (is_object($checklistitem)) {
    $values = $checklistitem->getItemContent();
    $value = $values[$checkListField->getFormFieldName()];
}



?>
<div class="form-group">
    <div class="form-check">
        <?php
        foreach ($checkListField->getAnswers() AS $answer) { ?>

            <?php VarDumper::dump($answer); die; ?>
            <br/>
            <input class="form-check-input" <?= ($checkListField->getRequired() == 1 ? 'required' : '') ?>
                        type="<?= $checkListField->getChecklistFieldType()->getFormType(); ?>"
                        name="<?= $checkListField->getId(); ?>"
                        value="<?= $answer->getId(); ?>"/>&nbsp;
            <label class="form-check-label">
                <?= $answer->getLabel(); ?>
            </label>
            <?php
        }
        ?>
        <div class="invalid-feedback">
            <?= $checkListField->getRequiredMessage(); ?>
        </div>
    </div>
</div>