<!-- Modal -->
<div class="modal fade" id="addChecklistItem" tabindex="-1" role="dialog" aria-labelledby="addChecklistItemLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h4 class="modal-title" id="addChecklistItemLabel">Add checklist item</h4>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <input type="hidden" name="id" id="checkListItemId" value=""/>
            <div class="modal-body">
                <?php foreach ($checkListFields AS $checkListField) { ?>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label><?php echo $checkListField->getName(); ?><?php echo($checkListField->getRequired() == 1 ? '*' : '') ?></label>


                                <?php
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'text') {
                                    echo $this->partial('check-list/check-list-item/partials/input-text.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'number') {
                                    echo $this->partial('check-list/check-list-item/partials/input-number.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'checkbox') {
                                    echo $this->partial('check-list/check-list-item/partials/input-checkbox.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'textarea') {
                                    echo $this->partial('check-list/check-list-item/partials/input-textarea.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'date') {
                                    echo $this->partial('check-list/check-list-item/partials/input-datum.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'email') {
                                    echo $this->partial('check-list/check-list-item/partials/input-email.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'time') {
                                    echo $this->partial('check-list/check-list-item/partials/input-time.phtml', array('checkListField' => $checkListField));
                                }
                                if ($checkListField->getChecklistFieldType()->getFormType() == 'url') {
                                    echo $this->partial('check-list/check-list-item/partials/input-url.phtml', array('checkListField' => $checkListField));
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <div class="modal-footer">
                <button type="button" id="addChecklistItemButton" class="btn btn-secondary">Opslaan</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#addChecklistItemOpen').on('click', function () {
            clearFormFields();
            $(function () {
                $('#addChecklistItem').modal('toggle');
            });
        });

        $(document).on('click', '.editChecklistItemOpen', function () {
            clearFormFields();
            var id = $(this).data('checklistitemid');
            $.ajax({
                url: '<?php echo $this->url('checklistajax', ['action' => 'getChecklistItem']); ?>',
                dataType: 'json',
                data: {
                    id: id
                },
                async: true,
                type: 'post',
                success: function (response) {
                    $('input#checkListItemId').val(id);


                    $.each(response.itemContent[id], function (index, value) {

                        var formField = $('form#CheckListItem input[name='+index+']');

                        if (formField.attr('type') == 'text') {
                            formField.val(value);
                        }
                        else if (formField.attr('type') == 'checkbox') {
                            $.each(formField, function () {
                                var checkBoxValue = parseInt($(this).val());
                                var arrayValues = _.toArray(value);
                                if(_.indexOf(arrayValues, checkBoxValue) > -1) {
                                    $(this).prop("checked", true);
                                } else {
                                    $(this).prop("false", true);
                                }

                            });
                        }
                    });

                    $(function () {
                        $('#addChecklistItem').modal('toggle');
                    });
                }
            });
        });

        //Click function to add/edit checklistitem
        $('#addChecklistItemButton').on('click', function () {
            //Get form data and serialize it
            var formData = $("form#CheckListItem").serialize();

            //Ajax call to add or edit checklist item. Based on given id.
            $.ajax({
                url: '<?php echo $this->url('checklistajax', ['action' => 'addChecklistItem']); ?>',
                dataType: 'json',
                data: {
                    id: <?= $checklist->getId(); ?>,
                    formData: formData
                },
                async: true,
                type: 'post',
                success: function (response) {

                    if($("#myTable tr.noCheclistItems").length > 0) {
                        $("#myTable tr.noCheclistItems").remove();
                    }

                    if (response.action == 'add') { //If action is add than add a new row

                        //Because we are adding a new row in the table we create a new row
                        var row = $('<tr id="checklistItem-' + response.checkListItemId + '">');
                        //Add checkbox for multiple delete
                        row.append($('<td class="text-center">').html('<input class="delete-item" type="checkbox" name="checked-items[]" value="' + response.checkListItemId + '"/>'));


                        $('#myTable').find('thead tr th.checklistFieldHeader').each(function(index){
                            var checkListFieldId = $(this).data('checklistfield');
                            var checkListItemField = response.item[checkListFieldId];
                            var content = '';
                            if(typeof checkListItemField != 'undefined') {

                                //Get item form type (text, checkbox, date, select etc.)
                                var itemFormType = Object.keys(checkListItemField.type)[0];

                                if (itemFormType == 'text') {
                                    content = checkListItemField.type.text;
                                }
                                else if (itemFormType == 'checkbox') {
                                    $.each(checkListItemField.type.checkbox, function (index, value) {
                                        content += '<i class="fas fa-check-square"></i> ' + value + '<br/>'
                                    });
                                }
                            }
                            row.append($('<td data-checklistfield="'+checkListFieldId+'" class="checklistField" id="checkListField-'+checkListFieldId+'">').html(content));
                        });

                        //Create edit button
                        var buttons = '<button data-checklistitemid="' + response.checkListItemId + '" class="btn btn-sm btn-secondary editChecklistItemOpen">';
                        buttons += '<i class="fas fa-edit"></i>';
                        buttons += '</button>&nbsp;';
                        buttons += '<button data-checklistitemid="' + response.checkListItemId + '" class="btn btn-sm btn-danger removeChecklistItemOpen ">';
                        buttons += '<i class="fas fa-trash-alt"></i>';
                        buttons += '</button>';
                        row.append($('<td class="text-center">').html(buttons));
                        $('#myTable > tbody#result').append(row);

                    } else { //If action is edit than edit a row with new values

                        $('#myTable').find('tr#checklistItem-' + response.checkListItemId + ' td.checklistField').each(function(index){
                            var checkListFieldId = $(this).data('checklistfield');
                            var checkListItemField = response.item[checkListFieldId];
                            var content = '';
                            if(typeof checkListItemField != 'undefined') {

                                var itemFormType = Object.keys(checkListItemField.type)[0];

                                if (itemFormType == 'text') {
                                    content = checkListItemField.type.text;
                                }
                                else if (itemFormType == 'checkbox') {
                                    $.each(checkListItemField.type.checkbox, function (index, value) {
                                        content += '<i class="fas fa-check-square"></i> ' + value + '<br/>'
                                    });
                                }
                            }

                            $(this).html(content);
                        });
                    }
                    $(function () {
                        $('#addChecklistItem').modal('toggle');
                    });
                }
            });
        });

        function clearFormFields() {
            $('form#CheckListItem input[type=text]').val('');
            $('form#CheckListItem input[type=date]').val('');
            $('form#CheckListItem input[type=number]').val('');
            $('form#CheckListItem input[type=hidden]').val('');
            $('form#CheckListItem textarea').val('');
            $('form#CheckListItem input[type=radio]').prop("checked", false);
            $('form#CheckListItem input[type=checkbox]').prop("checked", false);

        }
    });
</script>
