<!-- Modal -->
<?php
$form->setAttributes(array(
'autocomplete' => ($checklist->getAutocomplete() == 2? "on":"off")
));
?>
<div class="modal fade" id="addChecklistItem" tabindex="-1" aria-labelledby="addChecklistItemLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h4 class="modal-title" id="addChecklistItemLabel">Add checklist item</h4>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <?php echo $this->form()->openTag($form); ?>
            <input type="hidden" name="id" id="checkListItemId" value=""/>
            <div class="modal-body">
                <?php $this->checkListHelper()->showCheckListFields($checkListFields, $this); ?>
            </div>
            <div class="modal-footer">
                <button type="button" id="addChecklistItemButton" class="btn btn-secondary">Opslaan</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
        </div>
    </div>
</div>
