<!-- Modal -->
<div class="modal fade" id="exportModal" tabindex="-1" aria-labelledby="exportModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5 text-primary" id="exportModalLabel">Exporteer items</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="<?= $this->url('beheer/checklistitem', ['action' => 'export-list']); ?>" method="post">
                <div class="modal-body">

                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="filters" name="filters" value="1">
                        <label class="form-check-label" for="header">Add filters</label>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="freezeRow" name="freezeRow" value="1">
                        <label class="form-check-label" for="header">Freeze first row</label>
                    </div>
                    <input type="hidden" name="id" value="<?= $checklist->getId(); ?>"/>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="export" class="btn btn-secondary">Export</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
