<!-- Modal -->
<div class="modal fade" id="importFile" tabindex="-1" aria-labelledby="importModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5 text-primary" id="importModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="header" name="header" value="1">
                    <label class="form-check-label" for="header">Column headers in eerste rij</label>
                </div>
                <div class="input-group">
                    <label class="sr-only" for="inlineFormInputGroup">File</label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend input-group-addon">
                            <label class="input-group-text  btn btn-file">
                                Browse&hellip; <input type="file" name="importfile" accept=".xls,.xlsx"
                                                      style="display: none;" multiple>
                            </label>
                        </div>
                        <input type="text" class="form-control" name="importfileName" readonly>
                    </div>
                    <input type="hidden" name="checklistid" value="<?php echo $checklist->getId(); ?>"/>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="upload" class="btn btn-secondary">Upload</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>