<!-- Modal -->
<div class="modal fade" id="importFile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h4 class="modal-title" id="importFileLabel">Importeer excel bestand</h4>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="header" name="header" value="1">
                    <label class="form-check-label" for="header">Column headers in eerste rij</label>
                </div>
                <div class="input-group">
                    <label class="sr-only" for="inlineFormInputGroup">File</label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend input-group-addon">
                            <label class="input-group-text  btn btn-file">
                                Browse&hellip; <input type="file" name="importfile" accept=".xls,.xlsx"
                                                      style="display: none;" multiple>
                            </label>
                        </div>
                        <input type="text" class="form-control" name="importfileName" readonly>
                    </div>
                    <input type="hidden" name="checklistid" value="<?php echo $checklist->getId(); ?>"/>
                </div>
            </div>
            <div class="modal-footer">

                <button type="button" id="upload" class="btn btn-secondary">Upload</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>