<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <h2 class="mb-4">CHECKLIST: <?php echo $checklist->getName(); ?></h2>
                <?= $this->partial('partial/checklist-fields.phtml', ['checklist' => $checklist]) ?>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <h2 class="mb-4">Checklist fields</h2>
                <?php
                echo $this->partial('partial/add-checklist-field-form.phtml', [
                    'form' => $form,
                    'checklist' => $checklist,
                    'checkListField' => $checkListField,
                    'checkListFields' => $checkListFields
                ]);
                ?>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded p-4">
                <?php
                echo $this->partial('partial/answers-library.phtml',
                    ['answers' => $answers, 'formAnswer' => $formAnswer, 'searchLinks' => $searchLinks]);
                ?>
            </div>
        </div>
    </div>
</div>
