<?php
$this->headTitle('Add Checklist');
$this->mainMenu()->setActiveItemId('checklistbeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'CheckList' => $this->url('beheer/checklist', ['action' => 'add-field', 'id' => $checklist->getId()]),
    'Add CheckList field' => $this->url('beheer/checklist', ['action' => 'add'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">CHECKLIST: <?php echo $checklist->getName(); ?></h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Second Page Header -->
<div class="row">
    <h1 class="col">FIELDS</h1>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Volgorde</th>
                <th>Naam</th>
                <th>Type</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($checklist->getCheckListFields() AS $field) { ?>
                <tr>
                    <td><?php echo $field->getOrder(); ?></td>
                    <td><?php echo $field->getName(); ?></td>
                    <td><?php echo $field->getChecklistFieldType()->getName(); ?></td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-secondary" href="
                   <?= $this->url('beheer/checklist', ['action' => 'edit-field', 'id' => $field->getId()]); ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        &nbsp;
                        <a class="btn btn-sm btn-danger" href="
                   <?= $this->url('beheer/checklist', ['action' => 'delete-field', 'id' => $field->getId()]); ?>">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>


<!-- THIRD Page Header -->
<div class="row">
    <h1 class="col">CHECKLIST FIELDS</h1>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('order')); ?>
            <?php echo $this->formNumber($form->get('order')); ?>
            <?php echo $this->formElementErrors($form->get('checklistFieldType')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('name')); ?>
            <?php echo $this->formText($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('checklistFieldType')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('required')); ?>
            <?php echo $this->formCheckbox($form->get('required')); ?>
            <?php echo $this->formElementErrors($form->get('checklistFieldType')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('checklistFieldType')); ?>
            <?php echo $this->formSelect($form->get('checklistFieldType')); ?>
            <?php echo $this->formElementErrors($form->get('checklistFieldType')); ?>
        </div>
    </div>
</div>

<div class="row">
    <div class="col">
        <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
    </div>
    <div class="col text-right">
        <a href="<?php echo $this->url('beheer/checklist') ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>

<script>
    $("#fieldType").change(function () {
        var selectedValue = $(this).val();


    });
</script>