<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4 text-primary">Checklist archive</h2>
                </div>
                <div class="row g-4">
                    <div class="col-sm-6 col-md-6 col-xl-6">
                        <a class="btn btn-primary"
                           href="<?= $this->url('beheer/checklist', ['action' => 'index']) ?>">
                            <i class="fas fa-list-alt"></i> Checklist
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
                    <thead class="thead-dark">
                    <tr>
                        <th>Naam</th>
                        <th class="text-center"><i class="fas fa-cogs"></i></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (count($checklists) > 0) { ?>
                        <?php foreach ($checklists as $checkList) { ?>
                            <tr>
                                <td><?php echo $checkList->getName(); ?></td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-danger" href="
                           <?= $this->url('beheer/checklist', ['action' => 'delete', 'id' => $checkList->getId()]); ?>">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                    <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/checklist',
                                        ['action' => 'un-archief', 'id' => $checkList->getId()]); ?>">
                                        <i class="fas fa-undo"></i>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    <?php } else { ?>
                        <td colspan="2" class="text-center">Er zijn nog geen gearchiveerde afvinklijsten.</td>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  mt-4 p-4">
                <?= $this->paginationControl($checklists,
                    'Sliding',
                    'layout/paginator',
                    array('route' => 'beheer/checklist')) ?>
            </div>
        </div>
    </div>
</div>