<?php
$this->mainMenu()->setActiveItemId('checklist');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Checklist' => $this->url('beheer/checklist'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">CHECKLIST ARCHIEF</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Naam</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($checklists) > 0) { ?>
                <?php foreach ($checklists AS $checkList) { ?>
                    <tr>
                        <td><?php echo $checkList->getName(); ?></td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-danger" href="
                           <?= $this->url('beheer/checklist', ['action' => 'delete', 'id' => $checkList->getId()]); ?>">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'un-archief', 'id' => $checkList->getId()]); ?>">
                                <i class="fas fa-undo"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <td colspan="2" class="text-center">Er zijn nog geen gearchiveerde afvinklijsten.</td>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>