<?php
$this->mainMenu()->setActiveItemId('checklist');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Checklist' => $this->url('beheer/checklist'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">CHECKLIST BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <th>Naam</th>
            <th><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
        </tr>
        
        <?php if (count($checklists) > 0) { ?>
        <?php foreach ($checklists AS $checkList) { ?>
            <tr>
                <td><?php echo $checkList->getName(); ?></td>
                <td class="td-center">
                                  <a class="btn btn-primary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'delete', 'id' => $checkList->getId()]); ?>">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete permanent
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'un-archief', 'id' => $checkList->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Zet checklist terug
                        </a>
                    </td>
            </tr>
        <?php } ?>
        <?php } else { ?>
            <td colspan="2" class="text-center">Er zijn nog geen gearchiveerde afvinklijsten.</td>
        <?php } ?>
    </table>
</div>