<?php
$this->headTitle('Edit Checklist');
$this->mainMenu()->setActiveItemId('checklistbeheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'CheckList' => $this->url('beheer/checklist'),
    'Edit CheckList' => $this->url('beheer/checklist', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">EDIT CHECKLIST</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="col-lg-10 col-md-10 col-sm-10">
    <div class="form-group">
        <?php echo $this->formLabel($form->get('name')); ?>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php echo $this->formText($form->get('name')); ?>
        </div>
        <div class="col-sm-5 col-md-5 col-lg-5">
            <?php echo (count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;' ) ?>
        </div>
    </div>
    <div class="form-group">
            <?php echo $this->formLabel($form->get('public')); ?>
            <div class="radio">
                <?php echo $this->formRadio($form->get('public')); ?>
            </div>
            <div class="col-sm-5 col-md-5 col-lg-5">
                <?php echo (count($form->getMessages('public')) > 0 ? $form->getMessages('public')['isEmpty'] : '&nbsp;' ) ?>
            </div>
        </div>
</div>
<div class="col-sm-12 col-md-12 col-lg-12 " style="padding-left:0;">
    <button type="submit" id="submit" class="btn btn-primary">Opslaan</button> 
    <a href="<?php echo $this->url('beheer/checklist') ?>" class="btn btn-default" title="Annuleren">Annuleren</a>
</div>  
<?php echo $this->form()->closeTag($form); ?>


