<?php
$this->headTitle('Add Checklist');
$this->mainMenu()->setActiveItemId('checklistbeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'CheckList' => $this->url('beheer/checklist', ['action' => 'add-field', 'id' => $checklist->getId()]),
    'Edit CheckList field' => $this->url('beheer/checklist', ['action' => 'edit-field'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">CHECKLIST: <?php echo $checklist->getName(); ?></h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page Header -->
<div class="row">
    <h1 class="col">CHECKLIST FIELDS</h1>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('order')); ?>
            <?php echo $this->formNumber($form->get('order')); ?>
            <?php echo $this->formElementErrors($form->get('order')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('name')); ?>
            <?php echo $this->formText($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('required')); ?>
            <?php echo $this->formCheckbox($form->get('required')); ?>
            <?php echo $this->formElementErrors($form->get('required')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('checklistFieldType')); ?>
            <?php echo $this->formSelect($form->get('checklistFieldType')); ?>
            <?php echo $this->formElementErrors($form->get('checklistFieldType')); ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
    </div>
    <div class="col text-right">
        <a href="<?php echo $this->url('beheer/checklist') ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>

<script>
    $("#fieldType").change(function () {
        var selectedValue = $(this).val();
    });
</script>