<?php
$this->headTitle('Edit Checklist');
$this->mainMenu()->setActiveItemId('checklistbeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'CheckList' => $this->url('beheer/checklist'),
    'Edit CheckList' => $this->url('beheer/checklist', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'class' => 'form-horizontal',
    'enctype' => 'multipart/form-data'
));
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">EDIT CHECKLIST</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class="col">
        <div class="form-group">
            <?php echo $this->formLabel($form->get('name')); ?>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <?php echo $this->formText($form->get('name')); ?>
            </div>
            <div class="col-sm-5 col-md-5 col-lg-5">
                <?php echo(count($form->getMessages('name')) > 0 ? $form->getMessages('name')['isEmpty'] : '&nbsp;') ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('public')); ?>
            <div class="radio">
                <?php echo $this->formRadio($form->get('public')); ?>
            </div>
            <div class="col-sm-5 col-md-5 col-lg-5">
                <?php echo(count($form->getMessages('public')) > 0 ? $form->getMessages('public')['isEmpty'] : '&nbsp;') ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <button type="submit" id="submit" class="btn btn-dark">Opslaan</button>
    </div>
    <div class="col">
        <a href="<?php echo $this->url('beheer/checklist') ?>" class="btn btn-dark" title="Annuleren">Annuleren</a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>


