<?php
$this->headTitle('Checklists');
$this->mainMenu()->setActiveItemId('checklist');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Checklist' => $this->url('beheer/checklist'),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">CHECKLIST BEHEER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page header options -->
<div class="row mb-3">
    <div class="col">
        <a class="btn btn-secondary" href="
       <?= $this->url('beheer/checklist', ['action' => 'add']); ?>">
            <i class="fas fa-plus-square"></i> New Checklist
        </a>
        <a class="btn btn-secondary" href="
       <?= $this->url('beheer/checklist', ['action' => 'archive']); ?>">
            <i class="fas fa-archive"></i> Archief
        </a>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Naam</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($checkLists) > 0) { ?>
                <?php foreach ($checkLists AS $checkList) { ?>
                    <tr>
                        <td><?php echo $checkList->getName(); ?></td>
                        <td class="text-center">
                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'edit', 'id' => $checkList->getId()]); ?>">
                                <i class="fas fa-edit"></i>
                            </a>
                            &nbsp;
                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'show', 'id' => $checkList->getId()]); ?>">
                                <i class="fas fa-search"></i>
                            </a>
                            &nbsp;
                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'add-field', 'id' => $checkList->getId()]); ?>">
                                <i class="fas fa-plus-square"></i>
                            </a>
                            &nbsp;
                            <a class="btn btn-sm btn-secondary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'archief', 'id' => $checkList->getId()]); ?>">
                                <i class="fas fa-archive"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <td colspan="2" class="text-center">Er zijn nog geen afvinklijsten.</td>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>