<?php
$this->mainMenu()->setActiveItemId('checklist');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'Checklist' => $this->url('beheer/checklist'),
]);
?>
<hgroup id="headAdminTitle" class="col-sm-12 col-md-12 col-lg-12">
    <h1 id="index">CHECKLIST BEHEER</h1>
</hgroup>
<!-- Breadcrumbs -->
<div class="col-lg-12 col-md-12 col-sm-12">
    <?= $this->pageBreadcrumbs()->render(); ?>
</div>
<p class="col-lg-12 col-md-12 col-sm-12">
    <a class="btn btn-default" href="
       <?= $this->url('beheer/checklist', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nieuwe checklist
    </a>
</p>
<div class="col-lg-12 col-md-12 col-sm-12">
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <th>Naam</th>
            <th class="text-center"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></th>
        </tr>
        <?php if (count($checkLists) > 0) { ?>
        <?php foreach ($checkLists AS $checkList) { ?>
            <tr>
                <td><?php echo $checkList->getName(); ?></td>
                <td class="text-center">
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'edit', 'id' => $checkList->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'show', 'id' => $checkList->getId()]); ?>">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Toon
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'add-field', 'id' => $checkList->getId()]); ?>">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Voeg veld toe
                        </a>
                        &nbsp;
                        <a class="btn btn-primary" href="
                           <?= $this->url('beheer/checklist', ['action' => 'archief', 'id' => $checkList->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Archiveer
                        </a>
                    </td>
            </tr>
        <?php } ?>
        <?php } else { ?>
            <td colspan="2" class="text-center">Er zijn nog geen afvinklijsten.</td>
        <?php } ?>
    </table>
</div>