<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">Checklist(s)</h2>
                </div>
                <form name="searchEvents" method="post"
                      action="<?php echo $this->url('beheer/checklist',  ['action' => 'index']); ?>">
                    <div class="row g-4">
                        <div class="col-sm-6 col-md-6 col-xl-6">
                            <a class="btn btn-primary" href="<?= $this->url('beheer/checklist', ['action' => 'add']); ?>">
                                <i class="fas fa-plus-square"></i> New Checklist
                            </a>
                            <a class="btn btn-primary"
                               href="<?= $this->url('beheer/checklist', ['action' => 'archive']) ?>">
                                <i class="fas fa-archive"></i> Archief
                            </a>
                        </div>
                        <div class="col-sm-4 col-md-4 col-xl-4 text-end">
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                        <div class="col-sm-2 col-md-2 col-xl-2">
                            <input class="form-control" name="search" value="<?php echo $searchString; ?>"
                                   type="search"
                                   placeholder="Search" aria-label="Search">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <table class="table table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Naam</th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>
            <?php if (count($checkLists) > 0) { ?>
                <?php foreach ($checkLists AS $checkList) { ?>
                    <tr>
                        <td><?php echo $checkList->getName(); ?></td>
                        <td class="text-center">
                            <a class="btn btn-sm  btn-warning" href="
                           <?= $this->url('beheer/checklist', ['action' => 'edit', 'id' => $checkList->getId()]) ?>">
                                <i class="fas fa-edit"></i>
                            </a>
                            &nbsp;
                            <a class="btn btn-sm btn-success" href="
                           <?= $this->url('beheer/checklist', ['action' => 'add-field', 'id' => $checkList->getId()]) ?>">
                                <i class="fas fa-plus-square"></i>
                            </a>
                            &nbsp;
                            <a class="btn btn-sm btn-info" href="
                           <?= $this->url('beheer/checklist', ['action' => 'show', 'id' => $checkList->getId()]) ?>">
                                <i class="fas fa-list-alt"></i>
                            </a>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="
                           <?= $this->url('beheer/checklist', ['action' => 'archief', 'id' => $checkList->getId()]) ?>">
                                <i class="fas fa-archive"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <td colspan="2" class="text-center">Er zijn nog geen afvinklijsten.</td>
            <?php } ?>
            </tbody>
        </table>
            </div>
        </div>
    </div>
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  mt-4 p-4">
                <?= $this->paginationControl($checkLists,
                    'Sliding',
                    'layout/paginator',
                    array('route' => 'beheer/checklist')) ?>
            </div>
        </div>
    </div>
</div>
