<?php
$this->headTitle('Show Checklist');
$this->mainMenu()->setActiveItemId('checklistbeheer');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'CheckList' => $this->url('beheer/checklist'),
    'Show CheckList' => $this->url('beheer/checklist', ['action' => 'show'])
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">ITEMS FOR <?php echo $checklist->getName(); ?></h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<!-- Page header options -->
<div class="row mb-3">
    <div class="col">
        <a class="btn btn-danger" id="remove" href="#">
            <i class="fas fa-trash-alt"></i> Verwijder geselecteerde items
        </a>
        <!--
        <a class="btn btn-secondary" href="
       <?= $this->url('beheer/checklistitem', ['action' => 'add', 'id' => $checklist->getId()]); ?>">
            <i class="fas fa-plus-square"></i> Nieuwe checklist item
        </a>-->
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-secondary" id="addChecklistItemOpen">
            <i class="fas fa-plus-square"></i> Nieuwe checklist item
        </button>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exportFile">
            <i class="fas fa-upload"></i> Exporteer items
        </button>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#importFile">
            <i class="fas fa-upload"></i> Importeer items
        </button>
    </div>
</div>
<div class="row">
    <div class="col">
        <table id="myTable" class="table table-dark table-sm table-bordered table-hover table-striped">
            <thead class="thead-dark">
            <tr>
                <th class="text-center sorter-false"><input type="checkbox" id="checkAll" name="checkAll" value="1"/>
                </th>
                <?php foreach ($checklist->getCheckListFields() as $fields) { ?>
                    <th><?php echo $fields->getName(); ?></th>
                <?php } ?>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody id="result">
            <?php if (count($checklist->getCheckListItems()) > 0) { ?>
                <?php foreach ($checklist->getCheckListItems() AS $item) { ?>
                    <tr id="item-<?php echo $item->getId(); ?>">
                        <td class="text-center"><input class="delete-item" type="checkbox" name="checked-items[]"
                                                       value="<?php echo $item->getId(); ?>"/></td>
                        <?php foreach ($checklist->getCheckListFields() as $fields) { ?>
                            <td <?php echo($fields->getChecklistFieldType()->getFormType() == 'checkbox' ? 'class="text-center"' : '') ?> >
                                <?php
                                if ($fields->getChecklistFieldType()->getFormType() == 'checkbox') {
                                    if ($item->getItemContent()[$fields->getFormFieldName()] == 1) {
                                        echo '<i class="fas fa-check-square"></i>';
                                    } else {
                                        echo '<i class="far fa-square"></i>';
                                    }
                                } else {
                                    echo $item->getItemContent()[$fields->getFormFieldName()];
                                }
                                ?>
                            </td>
                        <?php } ?>
                        <td class="text-center">
                            <button data-checklistitemid="<?= $item->getId(); ?>" class="btn btn-sm btn-secondary editChecklistItemOpen">
                                <i class="fas fa-edit"></i>
                            </button>
                            <a class="btn btn-sm btn-danger" href="
                               <?= $this->url('beheer/checklistitem', ['action' => 'delete', 'id' => $item->getId()]); ?>">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr>
                    <td class="text-center" colspan="<?php echo count($checklist->getCheckListFields()) + 3 ?>">Er zijn
                        nog
                        geen checklist items.
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Import file -->
<?php
echo $this->partial('check-list/partial/import-file.phtml', array('checklist' => $checklist));
?>
<!-- End Import file -->

<!-- Export file -->
<?php
echo $this->partial('check-list/partial/export-file.phtml', array('checklist' => $checklist));
?>
<!-- End Export file -->

<!-- Export file -->
<?php
echo $this->partial('check-list/partial/add-checklist-item.phtml', array('checklist' => $checklist, 'form' => $form, 'checkListFields' => $checkListFields));
?>
<!-- End Export file -->


<script>
    $(document).ready(function () {
        $('#checkAll').change(function (e) {
            if ($(this).is(":checked")) {
                $("input.delete-item").each(function (i) {
                    $(this).prop('checked', true);
                });
            } else {
                $("input.delete-item").each(function () {
                    $(this).prop('checked', false);
                });
            }
        });
        /*
         * Click funtion to remove selected items
         */
        $('#remove').click(function (e) {
            e.preventDefault();
            var itemsToDelete = []
            $("input.delete-item").each(function (i) {
                if ($(this).is(":checked")) {
                    itemsToDelete.push($(this).val());
                }
            });

            if (itemsToDelete.length > 0) {
                var form_data = new FormData();
                form_data.append('itemsToDelete', itemsToDelete);

                $.ajax({
                    url: '<?php echo $this->url('checklistajax', ['action' => 'delete-items']); ?>',
                    dataType: 'json',
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: form_data,
                    async: true,
                    type: 'post',
                    success: function (response) {
                        console.log(response.error);

                        if (response.error === false) {
                            $(response.deletedItems).each(function (index, value) {
                                $('tr#item-' + value).slideUp("slow", function () {
                                    // Animation complete.
                                });
                            });
                            $('#checkAll').prop('checked', false);
                        } else {
                            alert(response.error_message);
                        }
                    }
                });
            }
        });
    });
</script>